name: "Automated Tests"

on: pull_request

jobs:
  jest:
    name: "Jest Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
