name: CoopEra Linting

on: 
  pull_request:
    paths:
      - "coopera/**"
      - ".github/workflows/**"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: "lts/hydrogen"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npm run lint:prettier:check
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: "lts/hydrogen"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npm run lint:eslint:check
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coopera
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: "lts/hydrogen"
          cache: npm
          cache-dependency-path: coopera/package-lock.json
      - run: npm ci
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
